name: Lint VBA

on:
  push:
    branches:
      - dev
      - master
  pull_request:
jobs:
  test-and-static-analysis:
    name: Test and Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      uses: Vba-actions/lint-vba@v1
    - name: ASCII
      run: python -c "import non_ascii; non_ascii.find_non_ascii('./src/Modules/Roots.bas')"
    - name: Test
      uses: Vba-actions/test-vba@dev
